CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_CUSTOMER_CONTACT ( 
    SK_CUSTOMER_CONTACT_KEY      NUMBER(38,0)      NOT NULL COMMENT 'Surrogate key for customer contact',
    SK_CUSTOMER_KEY              NUMBER(38,0)      NOT NULL COMMENT 'Surrogate key for customer',
    CONTACT_TYPE                 STRING            COMMENT 'Type of contact (e.g., email, phone)',
    CONTACT_VALUE                STRING            COMMENT 'Contact information value',
    IS_PRIMARY                   BOOLEAN           COMMENT 'Indicates if this is the primary contact',
    CURRENT_FLAG                 CHAR(1)           COMMENT 'Indicates if this is the current record',
    EFFECTIVE_FROM               TIMESTAMP_NTZ     NOT NULL COMMENT 'Start date of this record',
    EFFECTIVE_TO                 TIMESTAMP_NTZ     COMMENT 'End date of this record',
    IS_DELETED                   CHAR(1)           COMMENT 'Indicates if the record is deleted',
    CREATED_BY                   STRING            COMMENT 'User who created the record',
    UPDATED_BY                   STRING            COMMENT 'User who last updated the record',
    CREATE_DATE_TIME             TIMESTAMP_NTZ     COMMENT 'Timestamp when the record was created',
    UPDATE_DATE_TIME             TIMESTAMP_NTZ     COMMENT 'Timestamp when the record was last updated',
    DATA_SOURCE                  STRING            COMMENT 'Source of the data',
    CREATE_BATCH_ID              STRING            COMMENT 'Identifier for the batch creating the record',
    UPDATE_BATCH_ID              STRING            COMMENT 'Identifier for the batch updating the record',
    BUSINESS_COLUMN              STRING            COMMENT 'Business-specific column',
    CONTACT_ID                   NUMBER(38,0)      COMMENT 'Unique identifier for the contact',
    CUSTOMER_ID                  NUMBER(38,0)      COMMENT 'Unique identifier for the customer',
    CONTACT_METHOD               STRING            COMMENT 'Preferred method of contact',
    CONSTRAINT PK_DIM_CUSTOMER_CONTACT PRIMARY KEY (SK_CUSTOMER_CONTACT_KEY) 
) COMMENT = 'Dimension table for storing customer contact details';