CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_PRODUCT_TYPE (
    BUSINESS_COLUMN                 VARCHAR(64)                COMMENT 'Business-related column',
    CREATED_BY                      VARCHAR(64)                COMMENT 'User who created the record',
    CREATE_BATCH_ID                 BIGINT                     COMMENT 'Batch ID during creation',
    CREATE_DATE_TIME                TIMESTAMP_NTZ              COMMENT 'Creation timestamp',
    CURRENT_FLAG                    CHAR(1)                    COMMENT 'Indicates current status',
    CUSTOMER_ID                     INT                        COMMENT 'Identifier for the customer',
    CUSTOMER_SEGMENT                VARCHAR(50)                COMMENT 'Segment classification of the customer',
    CUSTOMER_STATUS                 VARCHAR(50)                COMMENT 'Status of the customer',
    CUSTOMER_TIMEZONE_OFFSET        VARCHAR(50)                COMMENT 'Timezone offset of the customer',
    DATA_SOURCE                     VARCHAR(64)                COMMENT 'Source of the data',
    DATE_OF_BIRTH                   VARCHAR(50)                COMMENT 'Customer birth date',
    DESCRIPTION                     VARCHAR(255)               COMMENT 'Detailed description',
    EFFECTIVE_FROM                  TIMESTAMP_NTZ NOT NULL     COMMENT 'Start of record validity',
    EFFECTIVE_TO                    TIMESTAMP_NTZ              COMMENT 'End of record validity',
    EMAIL_ADDRESS                   VARCHAR(50)                COMMENT 'Email address of the customer',
    FIRST_NAME                      VARCHAR(50)                COMMENT 'First name of the customer',
    GENDER                          VARCHAR(50)                COMMENT 'Gender of the customer',
    IS_DELETED                      CHAR(1)                    COMMENT 'Flag indicating soft deletion',
    LAST_NAME                       VARCHAR(50)                COMMENT 'Last name of the customer',
    MOBILE_NUMBER                   VARCHAR(50)                COMMENT 'Customer mobile number',
    NATIONAL_ID                     VARCHAR(50)                COMMENT 'National ID of the customer',
    PRODUCT_TYPE_CODE               VARCHAR(64)                COMMENT 'Product code',
    PRODUCT_TYPE_ID                 BIGINT                     COMMENT 'Product type identifier',
    PRODUCT_TYPE_NAME               VARCHAR(128)               COMMENT 'Product type name',
    REGISTRATION_DATE               VARCHAR(50)                COMMENT 'Date of customer registration',
    RISK_RATING                     VARCHAR(50)                COMMENT 'Customer risk rating',
    SK_PRODUCT_TYPE_KEY             BIGINT NOT NULL            COMMENT 'Surrogate key for product type',
    STATUS_ID                       BIGINT                     COMMENT 'Identifier for the status',
    UPDATED_BY                      VARCHAR(64)                COMMENT 'User who updated the record',
    UPDATE_BATCH_ID                 BIGINT                     COMMENT 'Batch ID during update',
    UPDATE_DATE_TIME                TIMESTAMP_NTZ              COMMENT 'Update timestamp',

    PRIMARY KEY (SK_PRODUCT_TYPE_KEY)
)