CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_ACCOUNT_BALANCE_TYPE (
    ACCOUNT_BALANCE_TYPE_ID  BIGINT COMMENT 'Primary key for account balance type',
    BALANCE_TYPE_CODE        VARCHAR(64) COMMENT 'Short code for balance type',
    BALANCE_TYPE_NAME        VARCHAR(128) COMMENT 'Full name of the balance type',
    BUSINESS_COLUMN          VARCHAR(64) COMMENT 'Business specific column',
    CREATED_BY               VARCHAR(64) COMMENT 'User who created the record',
    CREATE_BATCH_ID          BIGINT COMMENT 'Batch ID for record creation',
    CREATE_DATE_TIME         TIMESTAMP_NTZ COMMENT 'Timestamp of record creation',
    CURRENT_FLAG             CHAR(1) COMMENT 'Flag to indicate current status',
    DATA_SOURCE              VARCHAR(64) COMMENT 'Source of the data',
    DESCRIPTION              VARCHAR(255) COMMENT 'Description of the account balance type',
    EFFECTIVE_FROM           TIMESTAMP_NTZ NOT NULL COMMENT 'Start timestamp for the record effectiveness',
    EFFECTIVE_TO             TIMESTAMP_NTZ COMMENT 'End timestamp for the record effectiveness',
    IS_DELETED               CHAR(1) COMMENT 'Flag to indicate deletion status',
    SK_ACCOUNT_BALANCE_TYPE_KEY BIGINT NOT NULL COMMENT 'Surrogate key for account balance type',
    STATUS_CODE              VARCHAR(16) COMMENT 'Code indicating status of the record',
    UPDATED_BY               VARCHAR(64) COMMENT 'User who last updated the record',
    UPDATE_BATCH_ID          BIGINT COMMENT 'Batch ID for record update',
    UPDATE_DATE_TIME         TIMESTAMP_NTZ COMMENT 'Timestamp of last update',
    CONSTRAINT PK_DIM_ACCOUNT_BALANCE_TYPE PRIMARY KEY (SK_ACCOUNT_BALANCE_TYPE_KEY)
  ) COMMENT 'Dimension table storing account balance types metadata';