CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_DATE (
    SK_DATE_KEY            INTEGER                 NOT NULL COMMENT 'Surrogate key for the date dimension',
    FULL_DATE              DATE                    NOT NULL COMMENT 'Full date representation',
    DAY_NUMBER_IN_MONTH    SMALLINT                NOT NULL COMMENT 'Day number in the month',
    DAY_NUMBER_IN_YEAR     SMALLINT                NOT NULL COMMENT 'Day number in the year',
    DAY_NAME               VARCHAR(32)            NOT NULL COMMENT 'Name of the day',
    WEEK_NUMBER_IN_YEAR    SMALLINT                NOT NULL COMMENT 'Week number in the year',
    MONTH_NUMBER           SMALLINT                NOT NULL COMMENT 'Month number',
    MONTH_NAME             VARCHAR(32)            NOT NULL COMMENT 'Name of the month',
    QUARTER_NUMBER         SMALLINT                NOT NULL COMMENT 'Quarter number',
    YEAR_NUMBER            INTEGER                 NOT NULL COMMENT 'Year number',
    FISCAL_MONTH_NUMBER    SMALLINT                COMMENT 'Fiscal month number',
    FISCAL_QUARTER         SMALLINT                COMMENT 'Fiscal quarter',
    FISCAL_YEAR            INTEGER                 COMMENT 'Fiscal year',
    IS_WEEKEND             CHAR(1)                NOT NULL COMMENT 'Indicates if the day is a weekend',
    CREATED_BY             VARCHAR(64)            COMMENT 'User who created the record',
    UPDATED_BY             VARCHAR(64)            COMMENT 'User who last updated the record',
    CREATE_DATE_TIME       TIMESTAMP_NTZ           COMMENT 'Timestamp when the record was created',
    UPDATE_DATE_TIME       TIMESTAMP_NTZ           COMMENT 'Timestamp when the record was last updated',
    DATA_SOURCE            VARCHAR(64)            COMMENT 'Source of the data',
    CREATE_BATCH_ID        BIGINT                  COMMENT 'Batch ID during creation',
    UPDATE_BATCH_ID        BIGINT                  COMMENT 'Batch ID during last update',
    CURRENT_FLAG           CHAR(1)                COMMENT 'Flag indicating if the record is current',
    START_DATE             TIMESTAMP_NTZ           NOT NULL COMMENT 'Start date timestamp',
    END_DATE               TIMESTAMP_NTZ           COMMENT 'End date timestamp',
    IS_DELETED             CHAR(1)                COMMENT 'Flag indicating if the record is deleted',

    CONSTRAINT PK_DIM_DATE PRIMARY KEY (SK_DATE_KEY)
) COMMENT = 'Date Dimension Table';