CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_PRODUCT_TYPE (
    SK_PRODUCT_TYPE_KEY BIGINT NOT NULL COMMENT 'Surrogate Key for Product Type',
    PRODUCT_TYPE_CODE VARCHAR(64) COMMENT 'Code for the Product Type',
    PRODUCT_TYPE_NAME VARCHAR(128) COMMENT 'Name of the Product Type',
    DESCRIPTION VARCHAR(255) COMMENT 'Description of the Product Type',
    CURRENT_FLAG CHAR(1) COMMENT 'Flag to indicate current product type',
    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL COMMENT 'Start date of the product type',
    EFFECTIVE_TO TIMESTAMP_NTZ COMMENT 'End date of the product type',
    IS_DELETED CHAR(1) COMMENT 'Flag to indicate if the row is deleted',
    CREATED_BY VARCHAR(64) COMMENT 'User who created the record',
    UPDATED_BY VARCHAR(64) COMMENT 'User who last updated the record',
    CREATE_DATE_TIME TIMESTAMP_NTZ COMMENT 'Timestamp when the record was created',
    UPDATE_DATE_TIME TIMESTAMP_NTZ COMMENT 'Timestamp when the record was last updated',
    DATA_SOURCE VARCHAR(64) COMMENT 'Source of the data',
    CREATE_BATCH_ID BIGINT COMMENT 'Batch ID for the creation process',
    UPDATE_BATCH_ID BIGINT COMMENT 'Batch ID for the update process',
    PRODUCT_TYPE_ID BIGINT COMMENT 'Unique identifier for the Product Type',
    STATUS_ID BIGINT COMMENT 'Status ID associated with the Product Type',
    CUSTOMER_ID INTEGER COMMENT 'Customer identifier',
    FIRST_NAME VARCHAR(50) COMMENT 'First name of the customer',
    LAST_NAME VARCHAR(50) COMMENT 'Last name of the customer',
    GENDER VARCHAR(50) COMMENT 'Customer gender',
    NATIONAL_ID VARCHAR(50) COMMENT 'National identifier of the customer',
    CUSTOMER_TIMEZONE_OFFSET VARCHAR(50) COMMENT 'Timezone offset for the customer',
    REGISTRATION_DATE VARCHAR(50) COMMENT 'Date of customer registration',
    MOBILE_NUMBER VARCHAR(50) COMMENT 'Customer mobile number',
    EMAIL_ADDRESS VARCHAR(50) COMMENT 'Email address of the customer',
    CUSTOMER_STATUS VARCHAR(50) COMMENT 'Status of the customer',
    RISK_RATING VARCHAR(50) COMMENT 'Risk rating associated with the customer',
    CUSTOMER_SEGMENT VARCHAR(50) COMMENT 'Segment classification for the customer',
    BUSINESS_COLUMN VARCHAR(64) COMMENT 'Business-related column',
    DATE_OF_BIRTH VARCHAR(50) COMMENT 'Date of birth of the customer',
    CONSTRAINT PK_DIM_PRODUCT_TYPE PRIMARY KEY (SK_PRODUCT_TYPE_KEY)
)