CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_DATE (
    SK_DATE_KEY          INTEGER               NOT NULL COMMENT 'Surrogate key for date',
    FULL_DATE            DATE                  NOT NULL COMMENT 'Represents full date in YYYY-MM-DD format',
    DAY_NUMBER_IN_MONTH  SMALLINT              NOT NULL COMMENT 'Day number in the month',
    DAY_NUMBER_IN_YEAR   SMALLINT              NOT NULL COMMENT 'Day number in the year',
    DAY_NAME             VARCHAR(32)           NOT NULL COMMENT 'Name of the day',
    WEEK_NUMBER_IN_YEAR  SMALLINT              NOT NULL COMMENT 'Week number in the year',
    MONTH_NUMBER         SMALLINT              NOT NULL COMMENT 'Month number',
    MONTH_NAME           VARCHAR(32)           NOT NULL COMMENT 'Name of the month',
    QUARTER_NUMBER       SMALLINT              NOT NULL COMMENT 'Quarter number',
    YEAR_NUMBER          INTEGER               NOT NULL COMMENT 'Calendar year number',
    FISCAL_MONTH_NUMBER  SMALLINT              COMMENT 'Fiscal month number (nullable)',
    FISCAL_QUARTER       SMALLINT              COMMENT 'Fiscal quarter (nullable)',
    FISCAL_YEAR          INTEGER               COMMENT 'Fiscal year (nullable)',
    IS_WEEKEND           CHAR(1)               NOT NULL COMMENT 'Indicates if the date is a weekend (Y/N)',
    CREATED_BY           VARCHAR(64)           COMMENT 'User who created the record (nullable)',
    UPDATED_BY           VARCHAR(64)           COMMENT 'User who last updated the record (nullable)',
    CREATE_DATE_TIME     TIMESTAMP_NTZ(6)      COMMENT 'Record creation timestamp (nullable)',
    UPDATE_DATE_TIME     TIMESTAMP_NTZ(6)      COMMENT 'Record update timestamp (nullable)',
    DATA_SOURCE          VARCHAR(64)           COMMENT 'Source of the data (nullable)',
    CREATE_BATCH_ID      BIGINT                COMMENT 'Batch ID for record creation (nullable)',
    UPDATE_BATCH_ID      BIGINT                COMMENT 'Batch ID for record update (nullable)',
    CURRENT_FLAG         CHAR(1)               COMMENT 'Indicates if this is the current version (nullable)',
    START_DATE           TIMESTAMP_NTZ(6)      NOT NULL COMMENT 'Start date timestamp',
    END_DATE             TIMESTAMP_NTZ(6)      COMMENT 'End date timestamp (nullable)',
    IS_DELETED           CHAR(1)               COMMENT 'Indicates if the record is deleted (nullable)',
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (SK_DATE_KEY)
)