CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_ACCOUNT (
    ACCOUNT_ID VARCHAR(64) COMMENT 'Account identifier.',
    ACCOUNT_NAME VARCHAR(128) COMMENT 'Name of the account.',
    ACCOUNT_NUMBER VARCHAR(64) COMMENT 'Unique account number.',
    ACCOUNT_TYPE_ID NUMBER(38,0) COMMENT 'ID representing the account type.',
    BUSINESS_COLUMN VARCHAR(64) COMMENT 'General business-related details.',
    CLOSE_DATE DATE COMMENT 'Date when the account was closed.',
    CREATED_BY VARCHAR(64) COMMENT 'User who created the record.',
    CREATE_BATCH_ID NUMBER(38,0) COMMENT 'Batch ID for creation process.',
    CREATE_DATE_TIME TIMESTAMP_NTZ COMMENT 'Timestamp of record creation.',
    CURRENCY_CODE VARCHAR(64) COMMENT 'Currency code associated with the account.',
    CURRENT_FLAG CHAR(1) COMMENT 'Indicates if the record is current.',
    CUSTOMER_ID NUMBER(38,0) COMMENT 'Identifier for the customer.',
    DATA_SOURCE VARCHAR(64) COMMENT 'Data source of the record.',
    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL COMMENT 'Start time for record validity.',
    EFFECTIVE_TO TIMESTAMP_NTZ COMMENT 'End time for record validity.',
    IS_DELETED CHAR(1) COMMENT 'Flag for soft deletion status.',
    OPEN_DATE DATE COMMENT 'Date when the account was opened.',
    PRODUCT_ID NUMBER(38,0) COMMENT 'Identifier for the product.',
    SK_ACCOUNT_KEY NUMBER(38,0) NOT NULL COMMENT 'Surrogate key for the account.',
    SK_ACCOUNT_STATUS_KEY NUMBER(38,0) COMMENT 'Surrogate key for account status.',
    SK_ACCOUNT_TYPE_KEY NUMBER(38,0) COMMENT 'Surrogate key for account type.',
    SK_CUSTOMER_KEY NUMBER(38,0) COMMENT 'Surrogate key for customer.',
    SK_PRODUCT_KEY NUMBER(38,0) COMMENT 'Surrogate key for the product.',
    STATUS_ID NUMBER(38,0) COMMENT 'Identifier representing status.',
    UPDATED_BY VARCHAR(64) COMMENT 'User who updated the record.',
    UPDATE_BATCH_ID NUMBER(38,0) COMMENT 'Batch ID for update process.',
    UPDATE_DATE_TIME TIMESTAMP_NTZ COMMENT 'Timestamp of last update.',

    CONSTRAINT PK_DIM_ACCOUNT PRIMARY KEY (SK_ACCOUNT_KEY)
) COMMENT = 'DIM_ACCOUNT table containing details about customer accounts.';