CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_CUSTOMER_ADDRESS (
    SK_CUSTOMER_ADDRESS_KEY BIGINT NOT NULL,
    SK_CUSTOMER_KEY BIGINT NOT NULL,
    ADDRESS_ID BIGINT,
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    ADDRESS_STATUS VARCHAR(16),
    ADDRESS_TYPE VARCHAR(64),
    BUSINESS_COLUMN VARCHAR(64),
    CITY VARCHAR(128),
    STATE VARCHAR(128),
    POSTAL_CODE VARCHAR(64),
    COUNTRY VARCHAR(128),
    CURRENT_FLAG CHAR,
    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL,
    EFFECTIVE_TO TIMESTAMP_NTZ,
    IS_DELETED CHAR,
    CREATED_BY VARCHAR(64),
    UPDATED_BY VARCHAR(64),
    CREATE_DATE_TIME TIMESTAMP_NTZ,
    UPDATE_DATE_TIME TIMESTAMP_NTZ,
    DATA_SOURCE VARCHAR(64),
    CREATE_BATCH_ID VARCHAR(64),
    UPDATE_BATCH_ID VARCHAR(64),

    CONSTRAINT PK_DIM_CUSTOMER_ADDRESS PRIMARY KEY (SK_CUSTOMER_ADDRESS_KEY)
    -- "Primary key ensures unique identification of customer addresses"
)