CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_STAGE.PRODUCT_TYPE (
  PRODUCT_TYPE_ID BIGINT NOT NULL COMMENT 'Unique identifier for product type',
  PRODUCT_TYPE_CODE STRING NOT NULL COMMENT 'Code representing the product type',
  PRODUCT_TYPE_NAME STRING NOT NULL COMMENT 'Name of the product type',
  PRODUCT_DESCRIPTION STRING COMMENT 'Description for the product type',
  STATUS_ID BIGINT NOT NULL COMMENT 'Foreign key to PRODUCT_STATUS table',
  CREATED_AT TIMESTAMP_NTZ NOT NULL COMMENT 'Record creation timestamp',
  CREATED_BY STRING NOT NULL COMMENT 'User who created the record',
  UPDATED_AT TIMESTAMP_NTZ COMMENT 'Record update timestamp',
  UPDATED_BY STRING COMMENT 'User who last updated the record',
  STG_CREATED_AT TIMESTAMP_NTZ NOT NULL COMMENT 'Stage creation timestamp',
  STG_CREATED_BY STRING NOT NULL COMMENT 'Stage creator',
  STG_UPDATED_AT TIMESTAMP_NTZ COMMENT 'Stage update timestamp',
  STG_UPDATED_BY STRING COMMENT 'Stage updater',
  RISK_RATING STRING COMMENT 'Risk rating associated with the product type',
  CUSTOMER_ID NUMBER COMMENT 'Customer ID who owns this product',
  CUSTOMER_SEGMENT STRING COMMENT 'Segment to which customer belongs',
  CUSTOMER_STATUS STRING COMMENT 'Status of customer',
  CUSTOMER_TIMEZONE_OFFSET STRING COMMENT 'Customer timezone offset',
  REGISTRATION_DATE STRING COMMENT 'Product registration date',
  EMAIL_ADDRESS STRING COMMENT 'Email address of the customer',
  FIRST_NAME STRING COMMENT 'Customer first name',
  LAST_NAME STRING COMMENT 'Customer last name',
  MOBILE_NUMBER STRING COMMENT 'Mobile number of the customer',
  NATIONAL_ID STRING COMMENT 'National ID of the customer',
  GENDER STRING COMMENT 'Gender of the customer',
  DATE_OF_BIRTH STRING COMMENT 'Date of birth of the customer',

  CONSTRAINT PK_PRODUCT_TYPE PRIMARY KEY (PRODUCT_TYPE_ID),
  CONSTRAINT FK_PRODUCT_TYPE_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES adam_data_engg_fsi_demo.EDW_STAGE.PRODUCT_STATUS(STATUS_ID) 
) COMMENT = 'Table to store product type information with associated customer details and stage tracking';