CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_ACCOUNT_BALANCE_TYPE (
    ACCOUNT_BALANCE_TYPE_ID BIGINT,
    BALANCE_TYPE_CODE VARCHAR(64),
    BALANCE_TYPE_NAME VARCHAR(128),
    BUSINESS_COLUMN VARCHAR(64),
    CREATED_BY VARCHAR(64),
    CREATE_BATCH_ID BIGINT,
    CREATE_DATE_TIME TIMESTAMP_NTZ,
    CURRENT_FLAG CHAR(1),
    DATA_SOURCE VARCHAR(64),
    DESCRIPTION VARCHAR(255),
    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL,
    EFFECTIVE_TO TIMESTAMP_NTZ,
    IS_DELETED CHAR(1),
    SK_ACCOUNT_BALANCE_TYPE_KEY BIGINT NOT NULL,
    STATUS_CODE VARCHAR(16),
    UPDATED_BY VARCHAR(64),
    UPDATE_BATCH_ID BIGINT,
    UPDATE_DATE_TIME TIMESTAMP_NTZ,

    PRIMARY KEY (SK_ACCOUNT_BALANCE_TYPE_KEY)
)
COMMENT = 'This table stores account balance types with audit columns and dimensional attributes.'