CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_ACCOUNT_BALANCE_TYPE (
  ACCOUNT_BALANCE_TYPE_ID BIGINT COMMENT 'DB2 Data Type: BIGINT',
  BALANCE_TYPE_CODE VARCHAR(64) COMMENT 'DB2 Data Type: VARCHAR, Length: 64',
  BALANCE_TYPE_NAME VARCHAR(128) COMMENT 'DB2 Data Type: VARCHAR, Length: 128',
  BUSINESS_COLUMN VARCHAR(64) COMMENT 'DB2 Data Type: VARCHAR, Length: 64',
  CREATED_BY VARCHAR(64) COMMENT 'DB2 Data Type: VARCHAR, Length: 64',
  CREATE_BATCH_ID BIGINT COMMENT 'DB2 Data Type: BIGINT',
  CREATE_DATE_TIME TIMESTAMP_NTZ COMMENT 'DB2 Data Type: TIMESTAMP',
  CURRENT_FLAG CHAR(1) COMMENT 'DB2 Data Type: CHARACTER, Length: 1',
  DATA_SOURCE VARCHAR(64) COMMENT 'DB2 Data Type: VARCHAR, Length: 64',
  DESCRIPTION VARCHAR(255) COMMENT 'DB2 Data Type: VARCHAR, Length: 255',
  EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL COMMENT 'DB2 Data Type: TIMESTAMP',
  EFFECTIVE_TO TIMESTAMP_NTZ COMMENT 'DB2 Data Type: TIMESTAMP',
  IS_DELETED CHAR(1) COMMENT 'DB2 Data Type: CHARACTER, Length: 1',
  SK_ACCOUNT_BALANCE_TYPE_KEY BIGINT NOT NULL COMMENT 'DB2 Data Type: BIGINT',
  STATUS_CODE VARCHAR(16) COMMENT 'DB2 Data Type: VARCHAR, Length: 16',
  UPDATED_BY VARCHAR(64) COMMENT 'DB2 Data Type: VARCHAR, Length: 64',
  UPDATE_BATCH_ID BIGINT COMMENT 'DB2 Data Type: BIGINT',
  UPDATE_DATE_TIME TIMESTAMP_NTZ COMMENT 'DB2 Data Type: TIMESTAMP',

  CONSTRAINT PK_DIM_ACCOUNT_BALANCE_TYPE PRIMARY KEY (SK_ACCOUNT_BALANCE_TYPE_KEY)
);