CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_ACCOUNT (
    ACCOUNT_ID VARCHAR(64) COMMENT 'Unique identifier for the account',
    ACCOUNT_NAME VARCHAR(128) COMMENT 'Name of the account',
    ACCOUNT_NUMBER VARCHAR(64) COMMENT 'Number associated with the account',
    ACCOUNT_TYPE_ID BIGINT COMMENT 'Identifier for the type of account',
    BUSINESS_COLUMN VARCHAR(64) COMMENT 'Business-specific column',
    CLOSE_DATE DATE COMMENT 'Date when the account was closed',
    CREATED_BY VARCHAR(64) COMMENT 'User who created the record',
    CREATE_BATCH_ID BIGINT COMMENT 'Batch ID for creation',
    CREATE_DATE_TIME TIMESTAMP_NTZ COMMENT 'Timestamp when the record was created',
    CURRENCY_CODE VARCHAR(64) COMMENT 'Currency code for the account',
    CURRENT_FLAG CHAR(1) COMMENT 'Flag indicating the current state',
    CUSTOMER_ID BIGINT COMMENT 'Identifier for the customer',
    DATA_SOURCE VARCHAR(64) COMMENT 'Source of the data',
    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL COMMENT 'Start time of the record effectiveness',
    EFFECTIVE_TO TIMESTAMP_NTZ COMMENT 'End time of the record effectiveness',
    IS_DELETED CHAR(1) COMMENT 'Indicator for deleted record',
    OPEN_DATE DATE COMMENT 'Date when the account was opened',
    PRODUCT_ID BIGINT COMMENT 'Identifier for the product associated with the account',
    SK_ACCOUNT_KEY BIGINT NOT NULL COMMENT 'Surrogate key for account',
    SK_ACCOUNT_STATUS_KEY BIGINT COMMENT 'Surrogate key for account status',
    SK_ACCOUNT_TYPE_KEY BIGINT COMMENT 'Surrogate key for account type',
    SK_CUSTOMER_KEY BIGINT COMMENT 'Surrogate key for customer',
    SK_PRODUCT_KEY BIGINT COMMENT 'Surrogate key for product',
    STATUS_ID BIGINT COMMENT 'Identifier for the account status',
    UPDATED_BY VARCHAR(64) COMMENT 'User who last updated the record',
    UPDATE_BATCH_ID BIGINT COMMENT 'Batch ID for last update',
    UPDATE_DATE_TIME TIMESTAMP_NTZ COMMENT 'Timestamp when the record was last updated',
    CONSTRAINT PK_DIM_ACCOUNT PRIMARY KEY (SK_ACCOUNT_KEY)
) COMMENT = 'Dimensional table for account metadata';