CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_PRODUCT (
    BUSINESS_COLUMN          VARCHAR(64) COMMENT 'Business column description.',
    CREATED_BY               VARCHAR(64) COMMENT 'User who created the record.',
    CREATE_BATCH_ID          BIGINT COMMENT 'Batch ID during creation.',
    CREATE_DATE_TIME         TIMESTAMP_NTZ COMMENT 'Timestamp of record creation.',
    CURRENCY_CODE            VARCHAR(64) COMMENT 'Currency code information.',
    CURRENT_FLAG             CHAR(1) COMMENT 'Flag indicating current record.',
    DATA_SOURCE              VARCHAR(64) COMMENT 'Source of data.',
    EFFECTIVE_FROM           TIMESTAMP_NTZ COMMENT 'Effective from timestamp.',
    EFFECTIVE_FROM_DATE      DATE COMMENT 'Effective starting date.',
    EFFECTIVE_TO             TIMESTAMP_NTZ COMMENT 'Effective until timestamp.',
    EFFECTIVE_TO_DATE        DATE COMMENT 'Effective ending date.',
    IS_DELETED               CHAR(1) COMMENT 'Indicates if record is deleted.',
    PRODUCT_CATEGORY_ID      BIGINT COMMENT 'Product category identifier.',
    PRODUCT_CODE             VARCHAR(64) COMMENT 'Unique product code.',
    PRODUCT_ID               VARCHAR(64) COMMENT 'Primary identifier for product.',
    PRODUCT_NAME             VARCHAR(128) COMMENT 'Descriptive product name.',
    PRODUCT_STATUS_CODE      VARCHAR(64) COMMENT 'Status code of the product.',
    PRODUCT_TYPE_ID          BIGINT COMMENT 'Product type identifier.',
    SK_PRODUCT_CATEGORY_KEY  BIGINT COMMENT 'Surrogate key for product category.',
    SK_PRODUCT_KEY           BIGINT NOT NULL COMMENT 'Primary surrogate key for product.',
    SK_PRODUCT_TYPE_KEY      BIGINT COMMENT 'Surrogate key for product type.',
    STATUS_ID                BIGINT COMMENT 'Status identifier.',
    UPDATED_BY               VARCHAR(64) COMMENT 'User who last updated the record.',
    UPDATE_BATCH_ID          BIGINT COMMENT 'Batch ID during update.',
    UPDATE_DATE_TIME         TIMESTAMP_NTZ COMMENT 'Timestamp of last update.',

    CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (SK_PRODUCT_KEY)
)