CREATE OR REPLACE TABLE adam_data_engg_fsi_demo.EDW_MART.DIM_CUSTOMER (
    SK_CUSTOMER_KEY BIGINT NOT NULL COMMENT 'Surrogate Key for Customer',
    BUSINESS_COLUMN VARCHAR(64) NULL COMMENT 'Business-related column',
    CREATED_BY VARCHAR(64) NULL COMMENT 'User who created the record',
    CREATE_BATCH_ID VARCHAR(64) NULL COMMENT 'Batch ID for creation',
    CREATE_DATE_TIME TIMESTAMP NULL COMMENT 'Timestamp when the record was created',
    CURRENT_FLAG CHAR(1) NULL COMMENT 'Flag indicating current record',
    CUSTOMER_ID VARCHAR(64) NOT NULL COMMENT 'Unique Identifier for Customer',
    CUSTOMER_NAME VARCHAR(128) NULL COMMENT 'Name of the Customer',
    CUSTOMER_SEGMENT VARCHAR(64) NULL COMMENT 'Segment of the Customer',
    CUSTOMER_STATUS VARCHAR(16) NULL COMMENT 'Status of the Customer',
    CUSTOMER_TIMEZONE_OFFSET VARCHAR(8) NULL COMMENT 'Customer Time Zone Offset',
    CUSTOMER_TYPE VARCHAR(64) NULL COMMENT 'Type of Customer',
    DATA_SOURCE VARCHAR(64) NULL COMMENT 'Source of Data',
    DATE_OF_BIRTH DATE NULL COMMENT 'Customer Date of Birth',
    EFFECTIVE_FROM TIMESTAMP NOT NULL COMMENT 'Effective Start Date for the record',
    EFFECTIVE_TO TIMESTAMP NULL COMMENT 'Effective End Date for the record',
    EMAIL_ADDRESS VARCHAR(128) NULL COMMENT 'Customer Email Address',
    GENDER VARCHAR(16) NULL COMMENT 'Gender of the Customer',
    INCOME_LEVEL VARCHAR(64) NULL COMMENT 'Income Level of the Customer',
    IS_DELETED CHAR(1) NULL COMMENT 'Flag indicating if record is deleted',
    MARITAL_STATUS VARCHAR(64) NULL COMMENT 'Marital Status of the Customer',
    MOBILE_NUMBER VARCHAR(16) NULL COMMENT 'Customer Mobile Number',
    NATIONALITY VARCHAR(64) NULL COMMENT 'Nationality of the Customer',
    OCCUPATION VARCHAR(128) NULL COMMENT 'Occupation of the Customer',
    REGISTRATION_DATE TIMESTAMP NULL COMMENT 'Date when the Customer Registered',
    RESIDENCY_STATUS VARCHAR(64) NULL COMMENT 'Residency Status of the Customer',
    RISK_RATING VARCHAR(16) NULL COMMENT 'Risk Level of the Customer',
    UPDATED_BY VARCHAR(64) NULL COMMENT 'User who updated the record',
    UPDATE_BATCH_ID VARCHAR(64) NULL COMMENT 'Batch ID for update',
    UPDATE_DATE_TIME TIMESTAMP NULL COMMENT 'Timestamp when the record was updated',

    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (SK_CUSTOMER_KEY)
);